[package]
name = "lixiv-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonschema = "0.34.0"
petgraph = "0.8.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
